Repository MindMate-org/MindMate, pull requests merged in 2025-07, with the labels that each got.

#19 Feat/#3 address book layout
  app/(tabs)/address-book/index.tsx
  src/features/address-book/components/address-book-content.tsx
  src/features/address-book/components/address-book-image.tsx
  src/features/address-book/components/address-book-item.tsx
  src/features/address-book/components/address-book-label.tsx
  src/features/address-book/components/address-book-list.tsx.tsx
  src/features/address-book/components/address-book-name.tsx
  src/features/address-book/components/address-book-self-item.tsx
Labels: 💄 style

#24 Feat/#4 routine routing and base component
  app/(tabs)/routine/index.tsx
  app/(tabs)/schedule/index.tsx
  app/routine/[id].tsx
  app/routine/routineform.tsx
  package.json
  pnpm-lock.yaml
  src/components/ui/add-button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/label.tsx
  src/components/ui/modal.tsx
  src/constants/date.ts
  src/features/routine/components/AlarmTimePicker.tsx
  src/features/routine/components/RepeatInfoModal.tsx
  src/features/routine/components/RoutineListCard.tsx
  src/features/routine/components/SubRoutineTaskCard.tsx
  src/features/routine/components/SubRoutineTaskCheckCard.tsx
  src/utils/date.ts
Labels: ✨ feature

#26 Feat/#25 routine UI
  app/(tabs)/routine/index.tsx
  app/routine/[id].tsx
  app/routine/routineform.tsx
  src/components/ui/add-button.tsx
  src/features/routine/components/RoutineListCard.tsx
Labels: ✨ feature

#41 Feat/#38 search ux
  app/(tabs)/search/index.tsx
  app/(tabs)/search/search-form.tsx
  src/components/ui/search-input.tsx
  src/lib/media-services.ts
Labels: 💄 style, ✨ feature, 👻 강지수
